version: "3"
services:
  mongo:
    image: mongo:5.0.2
    ports:
      - "127.0.0.1:27017:27017"
    command: [ --replSet, rs0 ]
    volumes:
      - mongodb_data:/data/db
      - ./conf/mongo/01-replica-set.init.js:/docker-entrypoint-initdb.d/01-replica-set.init.js
    networks:
      - mongo

  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:8883:8883"
      - "127.0.0.1:15672:15672"
    volumes:
      - ./conf/rabbitmq/:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  mongo:
  rabbitmq:
