server:
  port: 8080

spring:
  application:
    name: silhouette
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: silhouette
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
