server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: ushadow
  data:
    mongodb:
      uri: mongodb://localhost:27017/ushadow
      database: ushadow
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
